# Generated by Django 3.1.3 on 2020-11-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0007_auto_20201120_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='steps',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
