# Generated by Django 3.1.3 on 2020-11-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0008_auto_20201120_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='prototype.ticket'),
        ),
    ]
