# Generated by Django 3.1.3 on 2020-12-07 23:39

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0009_auto_20201120_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=encrypted_fields.fields.EncryptedTextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='steps',
            field=encrypted_fields.fields.EncryptedTextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='description',
            field=encrypted_fields.fields.EncryptedTextField(),
        ),
    ]
